name: CI/CD for Services

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build and push Docker images for Service A
    - name: Build and push Service A
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/service-a:latest ./microservices/microservices/service-a
        docker push ${{ secrets.DOCKER_USERNAME }}/service-a:latest

    # Step 4: Build and push Docker images for Service B
    - name: Build and push Service B
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/service-b:latest ./microservices/microservices/service-b
        docker push ${{ secrets.DOCKER_USERNAME }}/service-b:latest

    # Step 5: Deploy to Kubernetes
    - name: Set up Kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Deploy to Kubernetes
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: |
        kubectl apply -f ./k8s/service-a-deployment.yaml
        kubectl apply -f ./k8s/service-a-service.yaml
        kubectl apply -f ./k8s/service-b-deployment.yaml
        kubectl apply -f ./k8s/service-b-service.yaml
